version: '3.8'
 
services:
  backend:
    restart: always
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./src:/src
    command: >
      sh -c "python3 manage.py migrate &&
        python3 manage.py runserver 0.0.0.0:8000"
    env_file:
      - ./.env
    networks:
      - djangonetwork
    depends_on:
      - database
             
  database:
    image: postgres:13-alpine
    env_file:
      - ./.env
    networks:
      - djangonetwork
    ports:
      - "5432:5432"
    
  redis:
    image: redis:alpine
    command: --requirepass redispass
    ports:
    - "6379:6379"
    networks:
      - djangonetwork

volumes:
  pgdata:

networks:
  djangonetwork: